### ISSUE TITLE
Mobile navigation button doesn't fit on the same line until the user scrolls

### ISSUE THREAD

**Issue by rjbeers** [codeconnector/codeconnector.github.io#48]
**Describe the bug**
Upon initial page load, the navigation button doesn't fit on the screen when viewing the website using a mobile device. Once the user scrolls down the page, the css adjusts and the menu fits.

**To Reproduce**
1. Go to https://codeconnector.io/volunteer or https://codeconnector.io/sponsor on a mobile device OR on chrome
2. If on mobile, you will immediately see the issue. If on chrome/firefox, open the developer tools
3. Click the button to view on a mobile device emulator
4. Choose a Samsung S9/10 or Iphone 8ish

**Expected behavior**
I would expect the menu to be on the right side of the CODE CONNECTOR title without going off the screen or being shifted to the next line.

**Screenshots**
<img width="377" alt="Screen Shot 2020-06-29 at 9 10 42 PM" src="https://user-images.githubusercontent.com/5741299/86071332-0063a580-ba4d-11ea-8a76-629857dead2a.png">

**Smartphone (please complete the following information):**
 - Device: Samsung S10e
 - OS: android 7 or 8 or something
 - Browser firefox
 - Version latest

**Additional context**
There's another issue affecting the landing page with Typed.js. I'll file another issue for that.

**Comment by moody2times** [comment]
I have taken a look at this issue. I identified the problem and came up with 3 solutions and can implement whichever solution meet your needs.

Solution 1:
The brand and the menu button are both in a flex container set to wrap. So, on the S9+ device where the container is too small to container both items in the same row, it wraps and the button gets pushed to the another row. However, when a user scrolls up the button jumps back up because then the font-size of the brand gets smaller and the container is able to fit both items in the same row. 
To fix this, I can change the value flex-wrap property to no-wrap or simply delete it and the page will be fine.

Solution 2:
The brand "CODE CONNECTOR" has a margin right of 1rem (16px) which can be removed to allow the items to be displayed in one row. This margin-right is redundant especially since the justify-content is set to space-between which will space the flex items anyways. 
To fix this, I will remove the margin-right of 1rem from the brand and fixes it.

Solution 3:
Reducing the font-size of the brand to 1.46em from 1.5em also creates enough space for the flex items to fit in one row.

RECOMMENDED SOLUTION
Solution 2 is a better solution since space-between and margin-right serve the same purpose getting rid of the margin-right will not affect the design one whit.

If you are satisfied with any of my solutions, then please assign this task to me.

**Comment by rjbeers** [comment]
@moody2times Sounds good to me. Just be sure to test on larger width breakpoints as well to ensure that the margin-right isn't needed at some higher screen resolution.

**Comment by moody2times** [comment]
Alright then, thanks.

**Comment by rjbeers** [comment]
This was fixed in https://github.com/codeconnector/codeconnector.github.io/pull/71.
