### ISSUE TITLE
On-click icon in footer for accessing the code connector slack community

### ISSUE THREAD

**Issue by brehberg** [codeconnector/codeconnector.github.io#59]
As a new learner about code connector, I would like to connect with more coders to accelerate my learning.

There are existing one click buttons on the site to send me to F, T, L, and Eventbrite on the "Get Involved" and "About" pages. (I know they are really on all pages)  Could we put a similar button to Code Connector slack? 

I actually recall clicking a link to get here that was part of a previous meetup invite.  

Just some similar to that, as I feel the conversation here can be more educational than those other "social" sites.

**Comment by rjbeers** [comment]
Drawing attention to the slack community makes sense. Adding the slack icon and link at the bottom makes sense to me.

We use Font Awesome throughout the site. Font Awesome provides the slack logo, so adding this link is only a few lines of code. Would you like to give it a shot?

**Comment by xanderyzwich** [comment]
We have a 'contact' link in the header. It might be beneficial to go with some fontawesome icons for mail, meetup, and slack links up there in place of 'contact'

**Comment by brehberg** [comment]
Those both sound like sound like great improvements to me.  I would also like to keep sight of a suggestion from slack by Dennis Kennetz who said:  Button could be “join our slack”. That might make it pretty clear :grinning:

What about this redesign.  

1) Current "Contact" button seems to drop you to a footer element regardless of the page.  Keep that behavior as is and with the same label or "Contact Us!" if you really want to change it :)

2) Take the link for the "Join the community" button out of "Our online community" section.  Move that link to the footer in the "Send word our way" section and relabel to to say "via Slack".  Also add the FontAwesome icon for slack to the very bottom toolbar and point it to the same link.  (consider to fix the copywrite to be 2020 while you are there)

3) Go back to the only "Join the community" button.  Keep the text as it is, but change the link.  Send the user to the same place as the contact button. OR keep it working as is directing to slack, but change the text label to say "Join our slack community"

Probably a few more lines of code, but most of them are basically known.  Just shuffle the cards around to stack the deck as we like it 👍

**Comment by rjbeers** [comment]
I'm convinced that we could add the slack logo and link to the very bottom next to the other social icons.

The rest isn't relevant to this github issue, but since the conversation is flowing...
* I'm not convinced `Join the community` should be changed.
* On https://codeconnector.io/learn, the `Sign up` button at the top should point directly to the slack invite like as other areas do.
* I'd like to rework the nav item for `Contact` and rethink how we would like to be contacted at the organization. By scrolling down the page, this nav item behavior doesn't match the rest. It also requires content to be added to every page that will be ignored on most pages. I'm not a fan of this approach.

**Comment by LittleSouken** [comment]
Acredito que vocês me conhecem, sabem das minhas poucas contribuições e muitas dificuldades e indisciplina, mas espero poder ser util.
